# Generated by Django 5.0.6 on 2024-07-29 12:19

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_section',
            field=wagtail.fields.StreamField([('about_body', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('subheading', wagtail.blocks.CharBlock(required=False)), ('paragraph', wagtail.blocks.RichTextBlock())]))], blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_section',
            field=wagtail.fields.StreamField([('carousel', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.TextBlock(required=False)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True),
        ),
    ]
