# Generated by Django 5.0.6 on 2024-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_featuretab_featuretaborderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tabs_section_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tabs_section_subheading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
