# Generated by Django 5.0.6 on 2024-07-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_tabs_section_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='gallery_section_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery_section_subheading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_section_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_section_subheading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
