# Generated by Django 5.0.6 on 2024-07-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_about_section_heading_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Icon Item', 'verbose_name_plural': 'Icon Items'},
        ),
    ]
