# Generated by Django 5.0.6 on 2024-08-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_gallerypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='image',
        ),
    ]
